name: Node CI

# trigger workflow when push on master branch
on: 
  push:
    branches:
      - master
      - test_github_action

# a workflow contain some jobs
jobs:
  build:
    name: BUILD WEBSITE
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm ci
        npm run build --if-present
        npm run test:unit
      env:
        CI: true

  deploy: 
    name: DEPLOY WEBSITE
    needs: [build]
    runs-on: ubuntu-latest
    
    steps:
      - name: ftp
        run: |
          npm run deploy $ftp_ip $ftp_port $ftp_user $ftp_pwd
        env: # environment variable
          ftp_ip: ${{ secrets.ftp_ip }}
          ftp_port: 22
          ftp_user: ${{ secrets.ftp_user }}
          ftp_pwd: ${{ secrets.ftp_pwd }}
    
